name: "CI :: Kogito Tooling"

on:
  pull_request:
    branches: "**"

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout kie-tooling-core"
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/kie-tooling-core
          fetch-depth: 0

      - name: "Checkout kogito-tooling"
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/kogito-tooling
          fetch-depth: 0
          repository: tiagobento/kogito-tooling
          ref: monorepo

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.2.0

      - name: "Setup kie-tooling-core environment"
        uses: ./kie-tooling-core-tooling/.github/actions/setup-env
        with:
          os: ${{ matrix.os }}
          path: ${{ github.workspace }}/kie-tooling-core

      - name: "Bootstrap and build kie-tooling-core"
        working-directory: ${{ github.workspace }}/kie-tooling-core
        env:
          KOGITO_TOOLING_BUILD_lint: "false"
          KOGITO_TOOLING_BUILD_test: "false"
        run: |
          lerna run build:prod --stream --no-private --since ${{ github.event.pull_request.base.sha }} --include-dependencies

      - name: "Setup kogito-tooling environment"
        uses: ./kogito-tooling/.github/actions/setup-env
        with:
          os: ${{ matrix.os }}
          path: ${{ github.workspace }}/kogito-tooling

      - name: "Link kie-tooling-core with kogito-tooling"
        working-directory: ${{ github.workspace }}/kie-tooling-core
        run: |
          lerna exec 'yarn pack' --stream --no-private --since ${{ github.event.pull_request.base.sha }} --include-dependencies
          npm --prefix ../kogito-tooling install ./packages/*/*.tgz --no-save --package-lock=false
          rm ./packages/*/*.tgz

      - name: "Build kogito-tooling"
        working-directory: ${{ github.workspace }}/kogito-tooling
        env:
          WEBPACK__minimize: "false"
          WEBPACK__tsLoaderTranspileOnly: "false"
          KOGITO_TOOLING_BUILD_lint: "false"
          KOGITO_TOOLING_BUILD_test: "true"
          KOGITO_TOOLING_BUILD_testIT: "true"
          DISPLAY: ":99.0"
          START_SERVER_AND_TEST_INSECURE: "true"
        run: |
          lerna run build:prod --stream --concurrency 1
