name: "CI"

on:
  pull_request:
    branches: "**"

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.2.0

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          os: ${{ matrix.os }}

      - name: "Build"
        env:
          KOGITO_TOOLING_BUILD_lint: "true"
          KOGITO_TOOLING_BUILD_test: "true"
        run: |
          yarn build:prod

      - name: "Check generated resources (you should commit those!)"
        shell: bash
        run: |
          git diff
          [ "0" == "$(git diff | wc -l | tr -d ' ')" ]

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-${{ runner.os }}
          if-no-files-found: warn
          path: |
            packages/*/dist
            examples/*/dist
