name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
